name: example
description: Example app for the JsonDynamicWidget library

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  automated_testing_framework: ^3.0.7
  device_info: ^2.0.2
  dotted_border: ^2.0.0-nullsafety.0
  flutter:
    sdk: flutter
  flutter_google_places: ^0.3.0
  flutter_google_street_view: ^0.1.1
  flutter_inappwebview: ^5.1.0
  flutter_svg: ^0.21.0-nullsafety.0
  flutter_webview_plugin: ^0.4.0
  geocoding: ^2.0.0
  geolocator: ^7.2.0
  get_it: ^7.1.3
  google_api_headers: ^1.1.0
  google_maps_flutter: ^2.0.6
  google_maps_flutter_web: ^0.3.0+2
  google_maps_webservice: ^0.0.20-nullsafety.5
  json_dynamic_widget:
    path: ../
  screenshot: ^1.2.3
  street_view_platform_interface: ^0.1.0
  webview_flutter: ^2.0.8
dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_override: null

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/pages/
    - assets/secrets/
    - assets/widgets/
  fonts:
    - family: lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
    - family: metal
      fonts:
        - asset: assets/fonts/MetalMania-Regular.ttf
